#!/bin/sh
if [[ "$2" == "$1" ]]
then
	echo Fehler: Parameter 1 = Parameter 2
else
if [ $# -eq 3 ]
then
	rm -R -f $2
	cp -R /home/randolf/android/kernel/AnyKernel $2 -f
	rm -R -f $2/.git
	cp $1/arch/arm/boot/zImage $2/kernel/.
	rm $2/system/lib/modules/* -f
	cp $1/drivers/net/wireless/bcm4325/wireless.ko $2/system/lib/modules/.
	cp $1/arch/arm/mach-msm/qdsp5/vocpcm.ko $2/system/lib/modules/.
#	cp $1/drivers/net/tun.ko $2/system/lib/modules/.
#	cp $1/fs/cifs/cifs.ko $2/system/lib/modules/.
#	cp $1/fs/fuse/fuse.ko $2/system/lib/modules/.
	sh /home/randolf/android/kernel/sign_kernel $2
	cp $2/$2-signed.zip $3/.
else
	if [ $# -eq 2 ]
	then
        	rm -R -f $2
	        cp -R /home/randolf/android/kernel/AnyKernel $2 -f
	        rm -R -f $2/.git
        	cp $1/arch/arm/boot/zImage $2/kernel/.
	        rm $2/system/lib/modules/* -f
        	cp $1/drivers/net/wireless/bcm4325/wireless.ko $2/system/lib/modules/.
#	        cp $1/drivers/net/tun.ko $2/system/lib/modules/.
#	        cp $1/fs/cifs/cifs.ko $2/system/lib/modules/.
#		cp $1/fs/fuse/fuse.ko $2/system/lib/modules/.
	        sh /home/randolf/android/kernel/sign_kernel $2
	else
	        echo "Verzeichnisnamen des Kernels und für das neue Anykernels angeben (ohne '/' am Ende)"
	        echo "Beispiel: anykernelmaker /kernel /NewAnyKernel"
	fi
fi
fi
