#!/bin/sh
if [ $# -eq 1 ]
then
	cd $1
	rm -f $1*
	zip -r $1.zip *
        /opt/Oracle_Java/jdk1.6.0_35/bin/java -jar /home/randolf/android-sdk-linux/tools/SignApp/signapk.jar /home/randolf/android-sdk-linux/tools/SignApp/testkey.x509.pem /home/randolf/android-sdk-linux/tools/SignApp/testkey.pk8 $1.zip $1-signed.zip
else
        echo "Verzeichnis des Anykernels angeben"
        echo "Beispiel: sign_kernel /kernel"
fi
